name: CI
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  python:
    if: ${{ hashFiles('**/*.py') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -U pip
      - run: pip install black ruff pytest || true
      - run: ruff check .
      - run: black --check .
      - run: pytest -q || true
  node:
    if: ${{ hashFiles('**/package.json') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci || npm i
      - run: npx prettier -c . || true
      - run: npx eslint . || true
